version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toortoor

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: toortoor

  http:
    image: nginx:stable-alpine
    container_name: web-nginx
    restart: always
    volumes:
      - "./www:/usr/share/nginx/html:ro"
      - "./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - 80:80
